//! Source-map inversion for one text run (Spike B). A run is corpus text with
//! no marks/structure — the atom the Typst emitter escapes into markup. The
//! question: can point↔corpus be recovered by *recomputing* the escape
//! transform, at cluster granularity, with no per-character stored table?
//!
//! Answer this file demonstrates: yes. The transform is character-local except
//! the `//`→`\/\/` rule (a 2-char coupling), which a 1-char lookahead absorbs.
//! Each corpus char maps to a contiguous generated byte span; inverting a byte
//! lands on the char that owns it (a byte inside `\*` inverts to the single `*`
//! — the cluster, never a sub-char position that has no caret).
//!
//! The [`escape_run`] here is an independent reimplementation of the backend's
//! `quillmark_typst::convert::escape_markup`; `tests/spike_b_sourcemap.rs`
//! asserts the two agree over a battery. That assertion *is* the run-alignment
//! tripwire the plan asks for — if the backend's escaper grows a rule this
//! doesn't mirror, the test fails.

use std::ops::Range;

/// Per-corpus-char generated bytes, built by one left-to-right scan.
pub struct RunMap {
    /// Cumulative generated byte offsets; `cum[i]..cum[i+1]` is char `i`'s span.
    /// `len() == chars + 1`.
    cum: Vec<usize>,
    /// The generated markup (escaped), for cross-checking / slicing.
    generated: String,
    /// Corpus chars, so an invert result can be reported as a char.
    chars: Vec<char>,
}

impl RunMap {
    /// Build the map for `run` by recomputing the escape transform. O(chars),
    /// no stored per-character table beyond the cumulative offsets (which are
    /// derivable on the fly — kept here only for O(log n) inversion).
    pub fn build(run: &str) -> Self {
        let chars: Vec<char> = run.chars().collect();
        let mut generated = String::with_capacity(run.len());
        let mut cum = Vec::with_capacity(chars.len() + 1);
        cum.push(0);

        let mut i = 0;
        while i < chars.len() {
            let c = chars[i];
            if c == '/' && chars.get(i + 1) == Some(&'/') {
                // The one 2-char coupling: `//` → `\/\/`, each slash → `\/`.
                generated.push_str("\\/");
                cum.push(generated.len());
                generated.push_str("\\/");
                cum.push(generated.len());
                i += 2;
            } else {
                generated.push_str(&escape_single(c));
                cum.push(generated.len());
                i += 1;
            }
        }
        RunMap {
            cum,
            generated,
            chars,
        }
    }

    /// The escaped markup this run generates.
    pub fn generated(&self) -> &str {
        &self.generated
    }

    pub fn char_count(&self) -> usize {
        self.chars.len()
    }

    /// Forward: corpus char index → generated byte span. Panics past the end.
    pub fn forward(&self, char_idx: usize) -> Range<usize> {
        self.cum[char_idx]..self.cum[char_idx + 1]
    }

    /// Invert: generated byte offset → the corpus char index that owns it
    /// (cluster-exact). A byte at or past the end clamps to the last char; the
    /// exact end offset maps to `char_count` (the caret-after-run position).
    pub fn invert(&self, gen_byte: usize) -> usize {
        if gen_byte >= *self.cum.last().unwrap() {
            return self.chars.len();
        }
        // Largest i with cum[i] <= gen_byte.
        match self.cum.binary_search(&gen_byte) {
            Ok(i) => i,
            Err(i) => i - 1,
        }
    }
}

/// The single-char cases of `escape_markup`. The `//` coupling is handled by
/// the caller's lookahead, so a lone `/` is passed through here.
fn escape_single(c: char) -> String {
    match c {
        '\\' => "\\\\".into(),
        '~' => "\\~".into(),
        '*' => "\\*".into(),
        '_' => "\\_".into(),
        '`' => "\\`".into(),
        '#' => "\\#".into(),
        '[' => "\\[".into(),
        ']' => "\\]".into(),
        '{' => "\\{".into(),
        '}' => "\\}".into(),
        '$' => "\\$".into(),
        '<' => "\\<".into(),
        '>' => "\\>".into(),
        '@' => "\\@".into(),
        other => other.to_string(),
    }
}

/// The full run escaper, for cross-checking against the backend's. Equivalent
/// to running [`escape_single`] with the `//` lookahead over the whole run.
pub fn escape_run(run: &str) -> String {
    RunMap::build(run).generated
}
