//! Spike B — source-map inversion + navigation. Each test is a claim in
//! `phase-0-finding-b-sourcemap.md`.
//!
//! Two halves:
//!  - **B1 (pure)** proves the corpus↔generated map for one text run is
//!    recoverable by *recomputing* the escape transform, cluster-exact, with no
//!    per-character stored table — and cross-checks the reimplementation
//!    against the shipped `quillmark_typst::convert::escape_markup` (the
//!    run-alignment tripwire).
//!  - **B2 (real render)** drives the actual Typst backend and confirms the
//!    span→byte→field resolution chain works on real typeset output via the
//!    public `regions()`/`field_at()` — grounding that the per-glyph `.1`
//!    lever (span_scan.rs:197) sits on top of a chain that already resolves.

use std::collections::HashMap;

use quillmark_core::{Backend, FileTreeNode, Quill};
use quillmark_richtext_spikes::sourcemap::{escape_run, RunMap};
use quillmark_typst::convert::escape_markup;
use quillmark_typst::TypstBackend;

// ── B1: escape-transform inversion is faithful and cluster-exact ────────────

/// The runs that exercise every escape construct, including the `//` coupling,
/// multibyte, and astral chars.
const RUNS: &[&str] = &[
    "plain text",
    "a*b_c`d#e",
    "brackets [x] braces {y} dollar $z",
    "angles <a> at @b tilde ~c",
    "a//b",   // the 2-char coupling
    "http://example.com/path",
    "back\\slash",
    "unicode 你好 世界",
    "astral 😀 and 👍🏽 clusters",
    "mixed *你*//@😀",
];

#[test]
fn reimplemented_escape_matches_the_shipped_escaper() {
    // THE tripwire: our per-char scan (with `//` lookahead) must reproduce the
    // backend's `escape_markup` byte-for-byte. If the backend grows an escape
    // rule this scan doesn't mirror, this fails — which is exactly the
    // "flags any escape construct that breaks run-alignment" the plan asks for.
    for run in RUNS {
        assert_eq!(
            escape_run(run),
            escape_markup(run),
            "run-alignment: reimplementation diverges from escape_markup on {run:?}"
        );
    }
}

#[test]
fn forward_and_invert_round_trip_every_char() {
    for run in RUNS {
        let map = RunMap::build(run);
        assert_eq!(map.generated(), escape_markup(run));
        // Every corpus char forward-maps to a byte span; the span's first byte
        // inverts back to that char.
        for i in 0..map.char_count() {
            let span = map.forward(i);
            assert!(span.start < span.end, "char {i} of {run:?} has a nonempty span");
            assert_eq!(map.invert(span.start), i, "invert∘forward == id at char {i} of {run:?}");
        }
        // The end-of-run byte maps to the caret-after position.
        assert_eq!(map.invert(map.generated().len()), map.char_count());
    }
}

#[test]
fn inversion_is_cluster_exact_not_sub_char() {
    // A corpus char that escapes to several generated bytes (`*` → `\*`) is one
    // cluster: EVERY byte of its generated span inverts to that single char.
    // There is no sub-char position a caret could occupy, so navigation lands
    // on the char, never between the backslash and the star.
    let map = RunMap::build("a*b");
    assert_eq!(map.generated(), "a\\*b");
    let star_span = map.forward(1); // the '*'
    assert_eq!(star_span, 1..3);
    for byte in star_span.clone() {
        assert_eq!(map.invert(byte), 1, "byte {byte} of `\\*` inverts to the '*' char");
    }

    // Same for a multibyte scalar: all 3 UTF-8 bytes of 你 invert to it.
    let map = RunMap::build("a你b");
    let cjk_span = map.forward(1);
    assert_eq!(cjk_span.len(), 3);
    for byte in cjk_span.clone() {
        assert_eq!(map.invert(byte), 1);
    }
}

#[test]
fn map_needs_no_per_character_table_only_the_run_text() {
    // "No per-character tables": the map is a pure function of the run text.
    // Rebuilding from the same text yields an identical map — nothing is
    // carried between runs, and the escape transform is recomputed, not stored.
    for run in RUNS {
        let a = RunMap::build(run);
        let b = RunMap::build(run);
        assert_eq!(a.generated(), b.generated());
        assert_eq!(a.char_count(), b.char_count());
        for i in 0..a.char_count() {
            assert_eq!(a.forward(i), b.forward(i));
        }
    }
}

// ── B2: the span-resolution chain works on real typeset output ──────────────

fn quill(yaml: &str, plate: &str) -> Quill {
    let mut files = HashMap::new();
    files.insert(
        "Quill.yaml".to_string(),
        FileTreeNode::File { contents: yaml.as_bytes().to_vec() },
    );
    files.insert(
        "plate.typ".to_string(),
        FileTreeNode::File { contents: plate.as_bytes().to_vec() },
    );
    Quill::from_tree(FileTreeNode::Directory { files }).expect("load quill")
}

const YAML: &str = r#"
quill:
  name: spike_b
  version: 0.1.0
  backend: typst
  description: source-map spike render
typst:
  plate_file: plate.typ
main:
  fields:
    body:
      type: markdown
      description: a markdown body whose escaped text we navigate
"#;

const PLATE: &str = r#"
#import "@local/quillmark-helper:0.1.0": data
#set page(width: 612pt, height: 792pt, margin: 72pt)
#set text(size: 12pt)

#data.body
"#;

#[test]
fn real_render_resolves_a_point_to_the_content_field() {
    // The content field carries escape-worthy characters (`*`, `#`, `~`) — the
    // same transform B1 inverts. On real typeset output, `regions()` produces a
    // box for the field and `field_at` resolves a point inside it back to the
    // field: the span→byte→window chain the per-char `.1` inversion extends.
    let data = serde_json::json!({
        "body": "The unit\\'s lethality \\* readiness improved ~ measurably during the exercise."
    });
    let session = TypstBackend.open(&quill(YAML, PLATE), &data).expect("open");
    let regions = session.regions();
    let body: Vec<_> = regions.iter().filter(|r| r.field == "body").collect();
    assert!(!body.is_empty(), "the body field surfaces a region: {regions:?}");
    let r = body[0];
    assert!(r.rect[2] > r.rect[0] && r.rect[3] > r.rect[1], "positive area: {:?}", r.rect);

    let cx = (r.rect[0] + r.rect[2]) / 2.0;
    let cy = (r.rect[1] + r.rect[3]) / 2.0;
    assert_eq!(
        session.field_at(r.page, cx, cy).as_deref(),
        Some("body"),
        "a point on the field's ink resolves via the span chain"
    );
}

#[test]
fn origin_less_ink_and_empty_space_are_nav_ignored() {
    // Navigation must ignore ink with no corpus origin. A click far outside any
    // field's text resolves to nothing — the forward direction's counterpart to
    // "list markers / package numbering are nav-ignored".
    let data = serde_json::json!({ "body": "One short paragraph of body text." });
    let session = TypstBackend.open(&quill(YAML, PLATE), &data).expect("open");
    assert_eq!(
        session.field_at(0, 5.0, 5.0),
        None,
        "a point in the top-left margin, off all field ink, resolves to nothing"
    );
}
