//! Corpus → Typst-markup emitter that records a per-segment source map (PR-D).
//!
//! The codegen tier of the richtext seam (Option A): the one place a source map
//! can be produced, because it is the only place that both lowers the corpus and
//! knows the resulting byte layout. It walks a [`RichText`] to Typst markup —
//! reusing [`escape_markup`]/[`escape_string`], never re-parsing markdown — and
//! records, per segment, the generated byte window plus one `(corpus ↔ gen)` pair
//! per text run.
//!
//! **Engine-off.** Nothing in the render path calls this yet;
//! [`mark_to_typst`](crate::convert::mark_to_typst) (`convert.rs`) stays the live
//! lowering. A parity suite (see `tests`) pins this walker byte-for-byte against
//! that oracle so PR-E can delete it.
//!
//! ## Grammar (parity with `mark_to_typst`, one intentional divergence)
//!
//! - **Segment.** A maximal run of lines joined by
//!   [`Line::continues`](quillmark_richtext::model::Line::continues) — one
//!   paragraph, one heading, one whole code fence, one island line. A region
//!   keys on one segment; this is what "paragraph-level" means against the corpus.
//! - **Blocks.** `Heading{level}` → `=`×`level`; a `continues` paragraph joins its
//!   lines with `#linebreak()`; a code fence buffers its lines into one
//!   `#raw(block: true, lang:, "…")`; a block island renders its slot.
//! - **Marks.** A boundary sweep with open priority `(start, longer-first,
//!   kind-ord)` and close-and-reopen at overlap boundaries (Peritext free overlap
//!   → properly nested Typst). `strong/emph/underline/strike` →
//!   `#strong[`/`#emph[`/`#underline[`/`#strike[`; `link{url}` → `#link("…")[`;
//!   `code` → `#raw("…")`. `anchor`/`unknown` emit nothing.
//! - **Islands.** `table` → `#table(columns:, align:, table.header(…), …)`;
//!   `image` → `#image("url", alt:)`; unknown types emit nothing.
//! - **Block quotes render** — the one intentional divergence from
//!   `mark_to_typst`, which flattens them: `Container::Quote` →
//!   `#quote(block: true)[…]` (a superset behavior, landed as a tested decision).
//!
//! ## The 2→4 escape coupling
//!
//! Each run records only its `(corpus, gen)` pair; per-char spans are
//! **recomputed** by a one-scan that treats `//`→`\/\/` as a 2-char/4-byte
//! cluster and every other char as its own. The `escape_tripwire` test pins that
//! scan against [`escape_markup`]/[`escape_string`] byte-for-byte, so a future
//! escape-rule change fails loud.

use crate::convert::{escape_markup, escape_string};
use quillmark_core::error::MAX_NESTING_DEPTH;
use quillmark_richtext::model::{
    Container, LineKind, MarkKind, RichText, ISLAND_SLOT,
};
use std::ops::Range;

/// The escape discipline a text run was generated under — the recomputation key
/// for inverting a run's per-char span. `//`→`\/\/` couples 2 corpus chars to 4
/// generated bytes under **both** disciplines; every other rule differs, so the
/// context picks which scan inverts a run.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EscapeCtx {
    /// [`escape_markup`] — Typst markup body (`\*`, `\#`, `\/\/`, …).
    Markup,
    /// [`escape_string`] — inside a `"…"` literal (`\"`, `\\`, `\n`, `\/\/` no-op).
    StringLit,
}

/// One segment's source map: its corpus range, its generated window, and the
/// per-text-run correspondence between them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SegmentMap {
    /// The segment's range in the corpus, in USV (Unicode scalar values).
    pub corpus: Range<usize>,
    /// The segment's window in [`EmittedContent::markup`], in bytes.
    pub gen: Range<usize>,
    /// One `(corpus USV range, gen byte range, escape context)` per text run —
    /// the plain-text spans between marks/islands/line-breaks. Structural bytes
    /// (delimiters, container syntax, `#linebreak()`) fall between runs and are
    /// covered by [`Self::gen`] but no run.
    pub runs: Vec<(Range<usize>, Range<usize>, EscapeCtx)>,
}

/// The emitter's output: the Typst markup plus its ordered per-segment source map.
#[derive(Debug, Clone)]
pub struct EmittedContent {
    /// The lowered Typst markup.
    pub markup: String,
    /// One entry per emitted segment, in generation order.
    pub segments: Vec<SegmentMap>,
}

/// Emission failures. The corpus is normally already within
/// [`MAX_NESTING_DEPTH`] (import capped it), so this fires only on a hand-built
/// corpus that skipped that guard — kept parallel to
/// `ConversionError::NestingTooDeep` so the two lowerings reject the same inputs.
#[derive(Debug, thiserror::Error)]
pub enum EmitError {
    /// Container nesting exceeded the maximum allowed.
    #[error("Nesting too deep: {depth} levels (max: {max} levels)")]
    NestingTooDeep {
        /// Actual depth.
        depth: usize,
        /// Maximum allowed.
        max: usize,
    },
}

/// Lower a corpus to Typst markup and its per-segment source map.
pub fn emit_richtext(rt: &RichText) -> Result<EmittedContent, EmitError> {
    let max_depth = rt
        .lines
        .iter()
        .map(|l| l.containers.len())
        .max()
        .unwrap_or(0);
    if max_depth > MAX_NESTING_DEPTH {
        return Err(EmitError::NestingTooDeep {
            depth: max_depth,
            max: MAX_NESTING_DEPTH,
        });
    }
    let mut e = Emit::new(rt);
    let n = rt.lines.len();
    e.emit_block_level(0..n, 0);
    Ok(EmittedContent {
        markup: e.out,
        segments: e.segments,
    })
}

// ---------------------------------------------------------------------------
// Emitter
// ---------------------------------------------------------------------------

struct Emit<'a> {
    rt: &'a RichText,
    /// Corpus text as USV, so a `[start, end)` USV range slices in O(1).
    chars: Vec<char>,
    /// Per line: its `[start, end)` USV range (text only, excluding the `\n`
    /// separators, which sit at each non-last line's `end`).
    line_usv: Vec<(usize, usize)>,
    out: String,
    segments: Vec<SegmentMap>,
    /// Whether `out` currently ends at a fresh line — mirrors `mark_to_typst`'s
    /// `end_newline`, so block separators land identically.
    end_newline: bool,
}

impl<'a> Emit<'a> {
    fn new(rt: &'a RichText) -> Self {
        let chars: Vec<char> = rt.text.chars().collect();
        let mut line_usv = Vec::with_capacity(rt.lines.len());
        let mut start = 0usize;
        for (i, c) in chars.iter().enumerate() {
            if *c == '\n' {
                line_usv.push((start, i));
                start = i + 1;
            }
        }
        line_usv.push((start, chars.len()));
        // Defensive: a malformed corpus (lines.len() != segments) still indexes.
        while line_usv.len() < rt.lines.len() {
            line_usv.push((chars.len(), chars.len()));
        }
        Emit {
            rt,
            chars,
            line_usv,
            out: String::new(),
            segments: Vec::new(),
            end_newline: true,
        }
    }

    // ---- block-tree walk (terminator model, mirrors mark_to_typst) ----

    /// Emit the sibling blocks in `range`, all sharing the container prefix of
    /// length `depth`. Leaf blocks terminate with `\n\n`; lists and quotes carry
    /// their own whitespace. This is the top-level / in-quote discipline; list
    /// *item* bodies use [`Self::emit_item_body`] instead.
    fn emit_block_level(&mut self, range: Range<usize>, depth: usize) {
        let mut i = range.start;
        while i < range.end {
            let cont = self.rt.lines[i].containers.get(depth).cloned();
            match cont {
                Some(Container::ListItem { ordered, start, .. }) => {
                    let j = self.list_run_end(range.clone(), depth, ordered, start, i);
                    self.emit_list(i..j, depth, ordered, start);
                    i = j;
                }
                Some(Container::Quote) => {
                    let j = self.quote_run_end(range.clone(), depth, i);
                    self.emit_quote(i..j, depth);
                    i = j;
                }
                None => {
                    let j = self.segment_end(range.clone(), depth, i);
                    self.emit_leaf_terminated(i..j, depth);
                    i = j;
                }
            }
        }
    }

    /// End of the leaf segment starting at `i` at `depth`: `i` plus every
    /// following line at the same depth that continues it (a hard-break run or a
    /// code fence's lines).
    fn segment_end(&self, range: Range<usize>, depth: usize, i: usize) -> usize {
        let mut j = i + 1;
        while j < range.end
            && self.rt.lines[j].containers.len() == depth
            && self.rt.lines[j].continues
        {
            j += 1;
        }
        j
    }

    /// End of the list run starting at `i`: the maximal span of lines whose
    /// container at `depth` is a `ListItem` of the same `(ordered, start)` shape.
    /// Different-shape adjacent lists stay separate (same-shape ones already
    /// merged at import).
    fn list_run_end(
        &self,
        range: Range<usize>,
        depth: usize,
        ordered: bool,
        start: u64,
        i: usize,
    ) -> usize {
        let mut j = i + 1;
        while j < range.end {
            match self.rt.lines[j].containers.get(depth) {
                Some(Container::ListItem {
                    ordered: o,
                    start: s,
                    ..
                }) if *o == ordered && *s == start => j += 1,
                _ => break,
            }
        }
        j
    }

    /// End of the quote run starting at `i`: the maximal span of lines whose
    /// container at `depth` is a `Quote`.
    fn quote_run_end(&self, range: Range<usize>, depth: usize, i: usize) -> usize {
        let mut j = i + 1;
        while j < range.end
            && matches!(
                self.rt.lines[j].containers.get(depth),
                Some(Container::Quote)
            )
        {
            j += 1;
        }
        j
    }

    /// A leaf block terminated with `\n\n`. An empty paragraph emits nothing (as
    /// `mark_to_typst` emits no paragraph for empty content); every other block —
    /// including an empty heading (`= `) or empty code fence — still renders.
    fn emit_leaf_terminated(&mut self, range: Range<usize>, depth: usize) {
        let first = &self.rt.lines[range.start];
        let (lo, _) = self.line_usv[range.start];
        let (_, hi) = self.line_usv[range.end - 1];
        if matches!(first.kind, LineKind::Para) && lo == hi {
            return;
        }
        self.emit_segment(range, depth);
        self.out.push_str("\n\n");
        self.end_newline = true;
    }

    /// A list: `mark_to_typst`'s Start(List) fresh-line guard, each item, then a
    /// trailing `\n` only when this is the outermost list (no ancestor list item).
    fn emit_list(&mut self, range: Range<usize>, depth: usize, ordered: bool, start: u64) {
        if !self.end_newline {
            self.out.push('\n');
            self.end_newline = true;
        }
        let outermost = !self.rt.lines[range.start].containers[..depth]
            .iter()
            .any(|c| matches!(c, Container::ListItem { .. }));
        let mut k = range.start;
        while k < range.end {
            let key = self.rt.lines[k].containers[depth].clone();
            let mut m = k + 1;
            while m < range.end && self.rt.lines[m].containers.get(depth) == Some(&key) {
                m += 1;
            }
            let ordinal = match &key {
                Container::ListItem { ordinal, .. } => *ordinal,
                _ => 0,
            };
            self.emit_item(k..m, depth, ordered, start, ordinal == 0);
            k = m;
        }
        if outermost {
            self.out.push('\n');
            self.end_newline = true;
        }
    }

    /// One list item: `<indent><marker>` then the item's body, then End(Item)'s
    /// `\n` fresh-line guard. `indent` is `2×depth`; the marker is `- ` (bullet),
    /// the explicit `N. ` on the first item of an ordered list starting off-1, or
    /// `+ ` (Typst auto-numbers `+` from the first item's number).
    fn emit_item(
        &mut self,
        range: Range<usize>,
        depth: usize,
        ordered: bool,
        start: u64,
        first: bool,
    ) {
        let indent = "  ".repeat(depth);
        self.out.push_str(&indent);
        if ordered {
            if first && start != 1 {
                self.out.push_str(&format!("{}. ", start));
            } else {
                self.out.push_str("+ ");
            }
        } else {
            self.out.push_str("- ");
        }
        self.end_newline = false;
        self.emit_item_body(range, depth + 1);
        if !self.end_newline {
            self.out.push('\n');
            self.end_newline = true;
        }
    }

    /// A list item's body at `content_depth` (`= depth+1`): the first block flows
    /// straight off the marker; each later block is preceded by a blank line and
    /// the continuation indent (`2×content_depth`), matching `mark_to_typst`'s
    /// `list_item_first_block` handling. Nested lists/quotes recurse.
    fn emit_item_body(&mut self, range: Range<usize>, content_depth: usize) {
        let cont_indent = "  ".repeat(content_depth);
        let mut first_block = true;
        let mut i = range.start;
        while i < range.end {
            let cont = self.rt.lines[i].containers.get(content_depth).cloned();
            match cont {
                Some(Container::ListItem { ordered, start, .. }) => {
                    let j = self.list_run_end(range.clone(), content_depth, ordered, start, i);
                    self.emit_list(i..j, content_depth, ordered, start);
                    i = j;
                }
                Some(Container::Quote) => {
                    let j = self.quote_run_end(range.clone(), content_depth, i);
                    self.emit_quote(i..j, content_depth);
                    i = j;
                }
                None => {
                    let j = self.segment_end(range.clone(), content_depth, i);
                    if !first_block {
                        // Continuation block: the previous block left one `\n`;
                        // this adds a second plus the indent → blank line + indent.
                        self.out.push('\n');
                        self.out.push_str(&cont_indent);
                        self.end_newline = false;
                    }
                    self.emit_segment(i..j, content_depth);
                    if !self.end_newline {
                        self.out.push('\n');
                        self.end_newline = true;
                    }
                    i = j;
                }
            }
            first_block = false;
        }
    }

    /// A block quote (the intentional divergence): `#quote(block: true)[…]`
    /// wrapping the quote's inner blocks, lowered under the block-level
    /// discipline. Not compared against `mark_to_typst`, which flattens quotes.
    fn emit_quote(&mut self, range: Range<usize>, depth: usize) {
        if !self.end_newline {
            self.out.push('\n');
        }
        self.out.push_str("#quote(block: true)[\n");
        self.end_newline = true;
        self.emit_block_level(range, depth + 1);
        self.out.push(']');
        self.out.push_str("\n\n");
        self.end_newline = true;
    }

    // ---- segment content (no terminator, no marker) ----

    /// Emit one leaf segment's markup and record its [`SegmentMap`]. Leaves
    /// `end_newline` false — the caller owns the terminator.
    fn emit_segment(&mut self, range: Range<usize>, _depth: usize) {
        let kind = self.rt.lines[range.start].kind.clone();
        let (lo, _) = self.line_usv[range.start];
        let (_, hi) = self.line_usv[range.end - 1];
        match kind {
            LineKind::Heading { level } => {
                self.out.push_str(&"=".repeat(level as usize));
                self.out.push(' ');
                let g0 = self.out.len();
                let runs = self.emit_inline(lo, hi);
                let g1 = self.out.len();
                self.segments.push(SegmentMap {
                    corpus: lo..hi,
                    gen: g0..g1,
                    runs,
                });
            }
            LineKind::Code { lang } => self.emit_code(range, lang.as_deref(), lo, hi),
            LineKind::Island | LineKind::Para => {
                let g0 = self.out.len();
                let runs = self.emit_inline(lo, hi);
                let g1 = self.out.len();
                self.segments.push(SegmentMap {
                    corpus: lo..hi,
                    gen: g0..g1,
                    runs,
                });
            }
        }
        self.end_newline = false;
    }

    /// A code fence: `#raw(block: true[, lang: "…"], "…")`. Every line's text
    /// rides in the one string literal joined by an escaped `\n`; each line's
    /// content is one `StringLit` run.
    fn emit_code(&mut self, range: Range<usize>, lang: Option<&str>, lo: usize, hi: usize) {
        let g0 = self.out.len();
        self.out.push_str("#raw(block: true");
        if let Some(l) = lang {
            self.out.push_str(", lang: \"");
            self.out.push_str(&escape_string(l));
            self.out.push('"');
        }
        self.out.push_str(", \"");
        let mut runs = Vec::new();
        for (idx, li) in range.clone().enumerate() {
            if idx > 0 {
                // Line separator: an escaped `\n`, structural (outside any run).
                self.out.push_str(&escape_string("\n"));
            }
            let (l0, l1) = self.line_usv[li];
            let content: String = self.chars[l0..l1].iter().collect();
            let rg0 = self.out.len();
            self.out.push_str(&escape_string(&content));
            let rg1 = self.out.len();
            runs.push((l0..l1, rg0..rg1, EscapeCtx::StringLit));
        }
        self.out.push_str("\")");
        let g1 = self.out.len();
        self.segments.push(SegmentMap {
            corpus: lo..hi,
            gen: g0..g1,
            runs,
        });
    }

    // ---- inline: marks + islands + line breaks, with the source map ----

    /// Emit the inline content of a segment's USV range `[lo, hi)`, returning its
    /// text runs. Wrapping marks nest via a close-and-reopen boundary sweep;
    /// `code` marks render atomically as `#raw("…")`; island slots render their
    /// island; interior `\n`s (continuation breaks) render as `#linebreak()`.
    fn emit_inline(&mut self, lo: usize, hi: usize) -> Vec<(Range<usize>, Range<usize>, EscapeCtx)> {
        let mut runs = Vec::new();

        // Wrapping marks (nest) and atomic code marks, clipped to [lo, hi).
        let mut wraps: Vec<Wrap> = Vec::new();
        let mut codes: Vec<(usize, usize)> = Vec::new();
        for m in &self.rt.marks {
            if m.end <= lo || m.start >= hi {
                continue;
            }
            let s = m.start.max(lo);
            let e = m.end.min(hi);
            if s >= e {
                continue;
            }
            match &m.kind {
                MarkKind::Code => codes.push((s, e)),
                MarkKind::Strong | MarkKind::Emph | MarkKind::Underline | MarkKind::Strike => {
                    wraps.push(Wrap {
                        start: s,
                        end: e,
                        ord: m.kind.ord(),
                        open: wrap_open(&m.kind),
                    });
                }
                MarkKind::Link { url } => wraps.push(Wrap {
                    start: s,
                    end: e,
                    ord: m.kind.ord(),
                    open: format!("#link(\"{}\")[", escape_string(url)),
                }),
                // Anchor / Unknown project to nothing.
                MarkKind::Anchor { .. } | MarkKind::Unknown { .. } => {}
            }
        }
        codes.sort_unstable();

        // (end, ord) for a mark on the open stack; ord tie-breaks reopen order.
        let mut stack: Vec<(usize, u8)> = Vec::new();
        // Parallel to `stack`: the close delimiter is always `]`.
        let mut pos = lo;
        while pos <= hi {
            // Close every mark ending at `pos`; reopen any deeper survivors that
            // do not (free overlap → proper nesting).
            if let Some(idx) = stack.iter().position(|&(end, _)| end == pos) {
                let mut reopen: Vec<(usize, u8)> = Vec::new();
                while stack.len() > idx {
                    let (end, ord) = stack.pop().unwrap();
                    self.out.push(']');
                    if end != pos {
                        reopen.push((end, ord));
                    }
                }
                for (end, ord) in reopen.into_iter().rev() {
                    self.out.push_str(&wrap_open_for(ord, &wraps, pos, end));
                    stack.push((end, ord));
                }
            }
            if pos == hi {
                break;
            }
            // Open marks starting at `pos`: longer span first, then kind-ord.
            let mut opening: Vec<&Wrap> = wraps.iter().filter(|w| w.start == pos).collect();
            opening.sort_by(|a, b| b.end.cmp(&a.end).then(a.ord.cmp(&b.ord)));
            for w in opening {
                self.out.push_str(&w.open);
                stack.push((w.end, w.ord));
            }

            let c = self.chars[pos];
            if c == '\n' {
                self.out.push_str("#linebreak()");
                pos += 1;
                continue;
            }
            if c == ISLAND_SLOT {
                let markup = self.island_markup(pos);
                self.out.push_str(&markup);
                pos += 1;
                continue;
            }
            if let Some(&(cs, ce)) = codes.iter().find(|(s, _)| *s == pos) {
                let content: String = self.chars[cs..ce].iter().collect();
                self.out.push_str("#raw(\"");
                let rg0 = self.out.len();
                self.out.push_str(&escape_string(&content));
                let rg1 = self.out.len();
                self.out.push_str("\")");
                runs.push((cs..ce, rg0..rg1, EscapeCtx::StringLit));
                pos = ce;
                continue;
            }
            // Plain text run up to the next boundary.
            let re = self.next_boundary(pos, hi, &wraps, &codes);
            let content: String = self.chars[pos..re].iter().collect();
            let rg0 = self.out.len();
            self.out.push_str(&escape_markup(&content));
            let rg1 = self.out.len();
            runs.push((pos..re, rg0..rg1, EscapeCtx::Markup));
            pos = re;
        }
        runs
    }

    /// The next position after `pos` at which a plain run must stop: any mark
    /// start/end, any code start, an interior `\n`, an island slot, or `hi`.
    fn next_boundary(&self, pos: usize, hi: usize, wraps: &[Wrap], codes: &[(usize, usize)]) -> usize {
        let mut p = pos + 1;
        while p < hi {
            let c = self.chars[p];
            if c == '\n' || c == ISLAND_SLOT {
                break;
            }
            if wraps.iter().any(|w| w.start == p || w.end == p) {
                break;
            }
            if codes.iter().any(|(s, _)| *s == p) {
                break;
            }
            p += 1;
        }
        p
    }

    /// The island backing the slot at USV position `pos`, rendered to Typst.
    fn island_markup(&self, pos: usize) -> String {
        let idx = self.chars[..pos].iter().filter(|c| **c == ISLAND_SLOT).count();
        let Some(isl) = self.rt.islands.get(idx) else {
            return String::new();
        };
        match isl.island_type.as_str() {
            "image" => image_markup(&isl.props),
            "table" => table_markup(&isl.props),
            // Unknown island types emit nothing (parallel to the HTML rule).
            _ => String::new(),
        }
    }
}

/// A wrapping mark clipped to a segment: its span, kind-ord tie-break, and open
/// delimiter (its close is always `]`).
struct Wrap {
    start: usize,
    end: usize,
    ord: u8,
    open: String,
}

fn wrap_open(kind: &MarkKind) -> String {
    match kind {
        MarkKind::Strong => "#strong[".to_string(),
        MarkKind::Emph => "#emph[".to_string(),
        MarkKind::Underline => "#underline[".to_string(),
        MarkKind::Strike => "#strike[".to_string(),
        _ => String::new(),
    }
}

/// The open delimiter for a to-be-reopened mark, recovered from the `wraps` list
/// by `(ord, end)`. A reopened mark covers `[pos, end)`, so it matches on `end`
/// and `ord`; the original `start` is irrelevant to the delimiter text.
fn wrap_open_for(ord: u8, wraps: &[Wrap], pos: usize, end: usize) -> String {
    wraps
        .iter()
        .find(|w| w.ord == ord && w.end == end && w.start <= pos)
        .map(|w| w.open.clone())
        .unwrap_or_default()
}

/// `#image("url"[, alt: "…"])` from an image island's props.
fn image_markup(props: &serde_json::Value) -> String {
    let url = props.get("url").and_then(|v| v.as_str()).unwrap_or("");
    let alt = props.get("alt").and_then(|v| v.as_str()).unwrap_or("");
    let mut out = format!("#image(\"{}\"", escape_string(url));
    if !alt.trim().is_empty() {
        out.push_str(&format!(", alt: \"{}\"", escape_string(alt.trim())));
    }
    out.push(')');
    out
}

/// `#table(columns:, align:, table.header(…), …)` from a table island's props,
/// matching `mark_to_typst`'s grammar. Cells are the stored raw source slices,
/// escaped as markup — faithful for plain cells; inline formatting inside a cell
/// is a known parity gap (Risk 3), since the engine-off emitter cannot re-parse
/// the cell's markdown.
fn table_markup(props: &serde_json::Value) -> String {
    let header = props.get("header").and_then(|v| v.as_array());
    let rows = props.get("rows").and_then(|v| v.as_array());
    let aligns = props.get("aligns").and_then(|v| v.as_array());
    let cols = header.map(|h| h.len()).unwrap_or(0);

    let cell = |v: &serde_json::Value| escape_markup(v.as_str().unwrap_or(""));

    let mut out = String::from("#table(\n");
    out.push_str(&format!("  columns: {},\n", cols));
    if let Some(al) = aligns {
        if al
            .iter()
            .any(|a| a.as_str().map(|s| s != "none").unwrap_or(false))
        {
            out.push_str("  align: (");
            for (i, a) in al.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                out.push_str(match a.as_str().unwrap_or("none") {
                    "left" => "left",
                    "center" => "center",
                    "right" => "right",
                    _ => "auto",
                });
            }
            out.push_str("),\n");
        }
    }
    out.push_str("  table.header(");
    if let Some(h) = header {
        for c in h {
            out.push('[');
            out.push_str(&cell(c));
            out.push_str("], ");
        }
    }
    out.push_str("),\n");
    if let Some(rs) = rows {
        for row in rs {
            if let Some(r) = row.as_array() {
                out.push_str("  ");
                for c in r {
                    out.push('[');
                    out.push_str(&cell(c));
                    out.push_str("], ");
                }
                out.push('\n');
            }
        }
    }
    out.push(')');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::convert::mark_to_typst;
    use quillmark_richtext::import::from_markdown;

    fn emit(md: &str) -> EmittedContent {
        let rt = from_markdown(md).expect("import");
        assert_eq!(rt.validate(), Ok(()), "corpus invariants for {md:?}");
        emit_richtext(&rt).expect("emit")
    }

    /// Inputs on which the emitter must byte-match `mark_to_typst`. Excludes the
    /// enumerated intentional diffs (block quotes) and Risk-3 residuals
    /// (formatted/escaped table cells) — those are asserted separately below.
    fn parity_inputs() -> Vec<&'static str> {
        vec![
            // headings
            "# Heading 1",
            "## Heading 2",
            "### Heading 3",
            "#### Heading 4",
            "##### Heading 5",
            "###### Heading 6",
            "## Heading with **bold** and _italic_",
            "# Heading with $math$ and #functions",
            "# First\n\n## Second\n\n### Third",
            "# Heading\n\nThis is a paragraph.",
            "## Code example: `fn main()`",
            "#",
            // paragraphs / breaks
            "This is a paragraph.",
            "First paragraph.\n\nSecond paragraph.",
            "Line one  \nLine two",
            "Line one\\\nLine two",
            "a  \nb  \nc",
            "Line one\nLine two",
            "This is some\ntext on multiple\nlines",
            "P1.\n\nP2.\n\nP3.\n\nP4.\n\nP5.",
            // inline formatting
            "This is **bold**, _italic_, and ~~strikethrough~~ text.",
            "**bold**",
            "__bolded__",
            "*italic*",
            "~~strike~~",
            "**bold _and italic_**",
            "**_strong then emph_**",
            "**bold**text",
            "a*sdfasd*f",
            "word**bold**more",
            "*Write y*our paragraphs here.",
            "**a** __b__ **c**",
            "This is <u>underlined</u> text.",
            "pre<u>mid</u>post",
            "<U>upper</U>",
            "before <span class=\"x\">inner</span> after",
            "line1<br>line2",
            // inline code
            "`code`",
            "Text with `inline code` here",
            "`*#$<>`",
            "`` `code` ``",
            // links
            "[Link text](https://example.com)",
            "Visit [our site](https://example.com) for more.",
            "[Link](https://example.com/foo_bar)",
            "[Link](#anchor)",
            "[*bold* link](https://example.com)",
            "[Click 🎉](https://example.com)",
            "Check out https://example.com for more.",
            "// This should not be a comment",
            "Some text // with slashes in the middle",
            // escaping
            "Typst uses * for bold and # for functions.",
            "Use [brackets] and $math$ symbols.",
            "Text {{ content }}",
            "Hello~World",
            "Use path/to/file for the file",
            "Path: C:\\\\Users\\\\file",
            // lists
            "- Item 1\n- Item 2\n- Item 3",
            "1. First\n2. Second\n3. Third",
            "3. Three\n4. Four\n5. Five",
            "0. Zero\n1. One",
            "1. a\n2. b\n\ntext\n\n5. c\n6. d",
            "- Item 1\n- Item 2\n  - Nested item\n- Item 3",
            "- Level 1\n  - Level 2\n    - Level 3",
            "- Bullet item\n\n1. Ordered item\n2. Another ordered",
            "- **Bold** item\n- _Italic_ item\n- `Code` item",
            "- First line.\n\n  Second line.",
            "- Para 1.\n\n  Para 2.\n\n  Para 3.",
            "- Item 1\n\n  More text.\n\n- Item 2",
            "1. First para.\n\n   Second para.\n\n2. Next item.",
            "1. First\n   - Nested bullet\n   - Another bullet\n2. Second",
            "- Item text\n\n  ```\n  code here\n  ```",
            "- First para.\n\n  ```\n  code\n  ```\n\n  After code.",
            // code fences
            "```rust\nfn main() {}\n```",
            "```\nhello\n```",
            "````\n```\nnested\n```\n````",
            "```\n*bold* #heading $math$\n```",
            "    fn main() {}\n    println!()",
            "```rust#evil\ncode\n```",
            "```c++\ncode\n```",
            // images
            "![alt text](path/to/img.png)",
            "![](x.png)",
            "![a *b* `c`](x.png)",
            // tables (plain cells only — formatted cells are a residual)
            "| Name | Age |\n|------|-----|\n| Alice | 30 |\n| Bob | 25 |",
            "| A | B |\n|---|---|\n| 1 | 2 |",
            "| L | C | R |\n|:---|:---:|---:|\n| a | b | c |",
            "| L | D | R |\n|:---|---|---:|\n| a | b | c |",
            "| Name | Value |\n|------|-------|\n",
            "| A | B | C |\n|---|---|---|\n| | | |",
            "| A | B | C |\n|---|---|---|\n| 1 | 2 |",
            "| A | B |\n|---|---|\n| 1 | 2 | 3 |",
            "| H |\n|:--|\n| x |",
            "| L | C | R | D |\n|:---|:---:|---:|---|\n| a | b | c | d |",
            "| A | B | C | D | E | F |\n|---|---|---|---|---|---|\n| 1 | 2 | 3 | 4 | 5 | 6 |",
            "- item1\n- item2\n\n| A |\n|---|\n| 1 |",
            "| Status |\n|--------|\n| ✅ Done |",
            "Before.\n\n| A |\n|---|\n| 1 |\n\nAfter.",
            "# Title\n\n| A |\n|---|\n| 1 |",
            // mixed
            "A paragraph with **bold** and a [link](https://example.com).\n\nAnother paragraph with `inline code`.\n\n- A list item\n- Another item",
            "# Title\n\nThis is a paragraph with **bold** and *italic* text.\n\n## Section\n\n- List item 1\n- List item 2 with [link](https://example.com)\n\nMore text with `inline code`.",
            // unicode
            "你好世界",
            "**你好** _世界_",
            "Hello 🎉 World 🚀",
            "مرحبا بالعالم",
        ]
    }

    #[test]
    fn parity_with_mark_to_typst() {
        let mut mismatches = Vec::new();
        for md in parity_inputs() {
            let got = emit(md).markup;
            let want = mark_to_typst(md).expect("oracle");
            if got != want {
                mismatches.push(format!(
                    "INPUT {md:?}\n  emit:   {got:?}\n  oracle: {want:?}"
                ));
            }
        }
        assert!(
            mismatches.is_empty(),
            "{} parity mismatch(es):\n{}",
            mismatches.len(),
            mismatches.join("\n")
        );
    }

    #[test]
    fn empty_and_blank_match_oracle() {
        for md in ["", "   ", "\n\n\n", "   \n   \n   "] {
            assert_eq!(emit(md).markup, mark_to_typst(md).unwrap(), "for {md:?}");
        }
    }

    // ---- intentional divergence: block quotes render ----

    #[test]
    fn block_quote_renders_not_flattened() {
        let out = emit("> quoted text").markup;
        assert!(
            out.contains("#quote(block: true)["),
            "quote must render, got {out:?}"
        );
        assert!(out.contains("quoted text"), "quote body present: {out:?}");
        // The divergence from the oracle, made explicit.
        assert_ne!(out, mark_to_typst("> quoted text").unwrap());
    }

    #[test]
    fn block_quote_multi_paragraph() {
        let out = emit("> one\n>\n> two").markup;
        assert!(out.contains("#quote(block: true)["));
        assert!(out.contains("one") && out.contains("two"));
    }

    // ---- known residuals (Risk 3): cataloged, not papered over ----

    /// A table cell carrying inline markdown does NOT reach byte parity: the
    /// corpus stores the raw source slice (`**bold**`), and the engine-off
    /// emitter escapes it as literal text rather than re-parsing to `#strong[…]`.
    #[test]
    fn residual_formatted_table_cell_diverges() {
        let md = "| Name | Note |\n|------|------|\n| **bold** | _italic_ |";
        let got = emit(md).markup;
        let want = mark_to_typst(md).unwrap();
        assert_ne!(got, want, "if this ever matches, promote it out of residuals");
        // The emitter escapes the raw slice as literal text.
        assert!(got.contains("\\*\\*bold\\*\\*"), "got {got:?}");
        assert!(want.contains("#strong[bold]"), "oracle renders it");
    }

    /// A cell with an escaped pipe keeps the backslash from the source slice,
    /// where the oracle (which parses the cell) drops it — same root cause.
    #[test]
    fn residual_escaped_pipe_table_cell_diverges() {
        let md = "| A |\n|---|\n| a\\|b |";
        assert_ne!(emit(md).markup, mark_to_typst(md).unwrap());
    }

    /// Coincident `strong`+`emph` over the *same* range lose their source
    /// nesting order at import: `***x***`, `_**x**_`, and `**_x_**` all normalize
    /// to the identical corpus (two coincident marks), yet the oracle renders
    /// each per its source nesting. The emitter nests canonically by kind-ord
    /// (`strong` outer), so it byte-matches the strong-outer source forms
    /// (`**_x_**`) but not the emph-outer ones. No tie-break can satisfy both —
    /// the distinguishing bit is gone from the corpus. Cataloged, not papered.
    #[test]
    fn residual_coincident_strong_emph_loses_source_order() {
        // strong-outer source form: byte-matches.
        let m = "**_x_**";
        assert_eq!(emit(m).markup, mark_to_typst(m).unwrap());
        assert_eq!(emit(m).markup, "#strong[#emph[x]]\n\n");
        // emph-outer source forms: same corpus as above, so the emitter still
        // emits strong-outer — a documented divergence from the oracle.
        for m in ["***x***", "_**x**_"] {
            assert_eq!(emit(m).markup, "#strong[#emph[x]]\n\n");
            assert_ne!(emit(m).markup, mark_to_typst(m).unwrap());
        }
    }

    /// An empty-text link (`[](url)`) is an *import* canonicalization, not an
    /// emit gap: its mark is zero-width, and `RichText::normalize` drops
    /// zero-width formatting marks (`link` is formatting). The corpus is then a
    /// blank paragraph, so the emitter yields "" while the oracle emits an empty
    /// `#link(...)[]`. Documented in `quillmark-richtext` (Spike-A rules).
    #[test]
    fn residual_empty_text_link_dropped_at_import() {
        let md = "[](https://example.com)";
        assert_eq!(emit(md).markup, "");
        assert!(mark_to_typst(md).unwrap().contains("#link("));
    }

    // ---- escape tripwire (Spike-B run alignment, productionized) ----

    /// Reconstruct a run's generated bytes by a one-scan that treats `//`→`\/\/`
    /// as a 2-char/4-byte cluster and every other char as its own cluster, then
    /// assert the reconstruction equals `escape_markup`/`escape_string`
    /// byte-for-byte. Fails loud if an escape rule ever changes.
    fn scan_reconstruct(run: &str, ctx: EscapeCtx) -> String {
        let chars: Vec<char> = run.chars().collect();
        let mut out = String::new();
        let mut i = 0;
        while i < chars.len() {
            // The `//`→`\/\/` coupling is a *markup* rule only; `escape_string`
            // leaves `//` untouched, so it clusters solely under `Markup`.
            if ctx == EscapeCtx::Markup && chars[i] == '/' && chars.get(i + 1) == Some(&'/') {
                out.push_str("\\/\\/");
                i += 2;
                continue;
            }
            let s: String = chars[i].to_string();
            out.push_str(&match ctx {
                EscapeCtx::Markup => escape_markup(&s),
                EscapeCtx::StringLit => escape_string(&s),
            });
            i += 1;
        }
        out
    }

    #[test]
    fn escape_tripwire_markup() {
        let samples = [
            "plain text",
            "https://example.com",
            "a // b // c",
            "///",
            "Use * for _bold_ and # for @refs",
            "{braces} [brackets] $math$ <tags>",
            "C:\\Users\\file",
            "tilde~and`backtick`",
            "你好 🎉 mixed",
            "file://path//to//x",
        ];
        for s in samples {
            assert_eq!(
                scan_reconstruct(s, EscapeCtx::Markup),
                escape_markup(s),
                "markup scan != escape_markup for {s:?}"
            );
        }
    }

    #[test]
    fn escape_tripwire_string_lit() {
        let samples = [
            "plain text",
            "https://example.com",
            "a // b",
            "say \"hi\"\nnow\ttab",
            "C:\\Users\\file",
            "control\x07bell",
            "你好 🎉 mixed",
            "trailing//",
        ];
        for s in samples {
            assert_eq!(
                scan_reconstruct(s, EscapeCtx::StringLit),
                escape_string(s),
                "string scan != escape_string for {s:?}"
            );
        }
    }

    /// Every recorded run's generated bytes equal the escape of its corpus
    /// substring — the source map is byte-accurate against the emitted markup.
    #[test]
    fn runs_map_corpus_to_generated_bytes() {
        for md in parity_inputs() {
            let rt = from_markdown(md).unwrap();
            let ec = emit_richtext(&rt).unwrap();
            let chars: Vec<char> = rt.text.chars().collect();
            for seg in &ec.segments {
                // Segment window is within the markup and non-decreasing.
                assert!(seg.gen.start <= seg.gen.end && seg.gen.end <= ec.markup.len());
                for (corpus, gen, ctx) in &seg.runs {
                    let src: String = chars[corpus.clone()].iter().collect();
                    let expect = match ctx {
                        EscapeCtx::Markup => escape_markup(&src),
                        EscapeCtx::StringLit => escape_string(&src),
                    };
                    assert_eq!(
                        &ec.markup[gen.clone()],
                        expect,
                        "run bytes mismatch in {md:?}"
                    );
                    // Runs sit inside their segment's generated window.
                    assert!(gen.start >= seg.gen.start && gen.end <= seg.gen.end);
                }
            }
        }
    }

    /// Free-overlapping marks (Peritext; never produced by import, only by an
    /// editor) lower to properly nested Typst via close-and-reopen at the overlap
    /// boundary. `strong[0,4)` over `emph[2,6)` on "abcdef" →
    /// `#strong[ab#emph[cd]]#emph[ef]`.
    #[test]
    fn overlapping_marks_close_and_reopen() {
        use quillmark_richtext::model::{Line, Mark};
        let mut rt = RichText {
            text: "abcdef".to_string(),
            lines: vec![Line {
                kind: LineKind::Para,
                containers: vec![],
                continues: false,
            }],
            marks: vec![
                Mark {
                    start: 0,
                    end: 4,
                    kind: MarkKind::Strong,
                },
                Mark {
                    start: 2,
                    end: 6,
                    kind: MarkKind::Emph,
                },
            ],
            islands: vec![],
        };
        rt.normalize();
        assert_eq!(rt.validate(), Ok(()));
        let out = emit_richtext(&rt).unwrap().markup;
        assert_eq!(out, "#strong[ab#emph[cd]]#emph[ef]\n\n");
        // Bracket-balanced regardless.
        assert_eq!(out.matches('[').count(), out.matches(']').count());
    }

    /// A paragraph is one segment even across a hard break; a heading and a code
    /// fence are each one segment.
    #[test]
    fn segment_shape() {
        assert_eq!(emit("a  \nb  \nc").segments.len(), 1, "hard-break paragraph");
        assert_eq!(
            emit("```\nl1\nl2\nl3\n```").segments.len(),
            1,
            "code fence"
        );
        // A three-item list is three segments (one per item paragraph).
        assert_eq!(emit("- a\n- b\n- c").segments.len(), 3);
    }
}
